# Generated by Django 2.2.3 on 2020-03-10 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=80)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('end_date', models.DateField(verbose_name='Date')),
            ],
        ),
    ]
