# Generated by Django 2.2.3 on 2020-01-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slogan', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=350)),
                ('ingredients', models.CharField(max_length=500)),
                ('cals', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('sat_fat', models.IntegerField()),
                ('trans_fat', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fiber', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('protien', models.IntegerField()),
                ('kids_menu', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Vegan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Soy_Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Nute_Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Lactose_Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Gluten_Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Egg_Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.Items')),
            ],
        ),
    ]
