# Generated by Django 2.2.3 on 2020-01-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nute_Free',
            new_name='Nut_Free',
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('entr', 'Entree'), ('side', 'Side'), ('dsrt', 'Dessert'), ('bev', 'Beverage')], default='entr', max_length=200),
        ),
    ]
