# Generated by Django 2.2.3 on 2020-01-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200122_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
    ]
