# Generated by Django 2.2.3 on 2020-01-28 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20200126_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet_Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_restriciton', models.CharField(choices=[('vegan', 'Vegan'), ('vegtrn', 'Vegetarian'), ('eggF', 'Egg-Free'), ('nutF', 'Nut-Free'), ('soyF', 'Soy-Free'), ('glutF', 'Gluten-Free'), ('lactF', 'Lactose-Free')], default='', max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.Items')),
            ],
        ),
        migrations.RemoveField(
            model_name='gluten_free',
            name='item',
        ),
        migrations.RemoveField(
            model_name='lactose_free',
            name='item',
        ),
        migrations.RemoveField(
            model_name='nut_free',
            name='item',
        ),
        migrations.RemoveField(
            model_name='soy_free',
            name='item',
        ),
        migrations.RemoveField(
            model_name='vegan',
            name='item',
        ),
        migrations.RemoveField(
            model_name='vegetarian',
            name='item',
        ),
        migrations.DeleteModel(
            name='Egg_Free',
        ),
        migrations.DeleteModel(
            name='Gluten_Free',
        ),
        migrations.DeleteModel(
            name='Lactose_Free',
        ),
        migrations.DeleteModel(
            name='Nut_Free',
        ),
        migrations.DeleteModel(
            name='Soy_Free',
        ),
        migrations.DeleteModel(
            name='Vegan',
        ),
        migrations.DeleteModel(
            name='Vegetarian',
        ),
    ]
