# Generated by Django 2.2.3 on 2020-01-28 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20200128_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet_restriction',
            old_name='diet_restriciton',
            new_name='diet_restriction',
        ),
    ]
