# Generated by Django 2.2.3 on 2020-01-29 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200128_0158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diet_restriction',
            unique_together={('item', 'diet_restriction')},
        ),
    ]
